name: prayer_times_helper
description: A simple Flutter package to get today's Islamic prayer times and the next upcoming prayer.
version: 1.1.0
homepage: https://github.com/Muhaiminkpm/prayer_times_helper
repository: https://github.com/Muhaiminkpm/prayer_times_helper


environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  # This section is required even if empty to avoid pubspec warnings
